// Code generated by protoc-gen-go.
// source: lobby.proto
// DO NOT EDIT!

/*
Package grtsproto is a generated protocol buffer package.

It is generated from these files:
	lobby.proto

It has these top-level messages:
	Connected
	JoinedGame
	ChangeName
*/
package grtsproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Server -> Client
type Connected struct {
	Event    string `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	PlayerId uint32 `protobuf:"varint,2,opt,name=player_id" json:"player_id,omitempty"`
}

func (m *Connected) Reset()                    { *m = Connected{} }
func (m *Connected) String() string            { return proto.CompactTextString(m) }
func (*Connected) ProtoMessage()               {}
func (*Connected) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type JoinedGame struct {
	Event  string `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	GameId uint32 `protobuf:"varint,2,opt,name=game_id" json:"game_id,omitempty"`
}

func (m *JoinedGame) Reset()                    { *m = JoinedGame{} }
func (m *JoinedGame) String() string            { return proto.CompactTextString(m) }
func (*JoinedGame) ProtoMessage()               {}
func (*JoinedGame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Client -> Server
type ChangeName struct {
	Event string `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ChangeName) Reset()                    { *m = ChangeName{} }
func (m *ChangeName) String() string            { return proto.CompactTextString(m) }
func (*ChangeName) ProtoMessage()               {}
func (*ChangeName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Connected)(nil), "grtsproto.Connected")
	proto.RegisterType((*JoinedGame)(nil), "grtsproto.JoinedGame")
	proto.RegisterType((*ChangeName)(nil), "grtsproto.ChangeName")
}

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0x4a,
	0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x2f, 0x2a, 0x29, 0x06, 0x33, 0x95,
	0x74, 0xb9, 0x38, 0x9d, 0xf3, 0xf3, 0xf2, 0x52, 0x93, 0x4b, 0x52, 0x53, 0x84, 0x78, 0xb9, 0x58,
	0x53, 0xcb, 0x52, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x85, 0x04, 0xb9, 0x38, 0x0b,
	0x72, 0x12, 0x2b, 0x53, 0x8b, 0xe2, 0x33, 0x53, 0x24, 0x98, 0x80, 0x42, 0xbc, 0x4a, 0x3a, 0x5c,
	0x5c, 0x5e, 0xf9, 0x99, 0x79, 0xa9, 0x29, 0xee, 0x89, 0xb9, 0xa9, 0xe8, 0xea, 0xf9, 0xb9, 0xd8,
	0xd3, 0x81, 0xc2, 0x08, 0xd5, 0x9a, 0x5c, 0x5c, 0xce, 0x19, 0x89, 0x79, 0xe9, 0xa9, 0x7e, 0x58,
	0x54, 0xf3, 0x70, 0xb1, 0xe4, 0x01, 0x85, 0xc1, 0x4a, 0x39, 0x93, 0xd8, 0xc0, 0xce, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xbf, 0x2e, 0xb1, 0xa8, 0x00, 0x00, 0x00,
}
